### ISSUE TITLE
`not OperaMobile all` query doesn't work

### ISSUE THREAD

**Issue by emirotin** [browserslist/browserslist#482] opened 2020-04-27 16:02 UTC
```
"browserslist": [
    "last 2 versions",
    "not dead",
    "> 1%",
    "not IE <= 11",
    "not OperaMini all",
    "not OperaMobile all"
  ],
```

```
❯ npx browserslist --version
browserslist 4.12.0

❯ npx browserslist
browserslist: Unknown browser query `OperaMobile all`. Maybe you are using old Browserslist or made typo in query.
```

Same with `op_mob` selector

As you can see the similar selector for `OperaMini` works.

Similarly `not IE all` doesn't work while `not IE <= 11` works. `not OperaMobile > 0` does work as well.

**Comment by ai** [comment] 2020-04-27 16:07
`not IE all` should not work. `all` is a strange version, which Can I Use uses for Opera Mini.

Can you send PR with adding `all` version to https://github.com/browserslist/browserslist/blob/master/index.js#L1067 and tests?

**Comment by emirotin** [comment] 2020-04-27 16:16
Ok makes sense though obviously this is an implementation detail which
would be nice to hide.

Will try to add it, it also likely makes sense to have the synonymous * and
every.

**Comment by ai** [comment] 2020-04-27 16:23
I prefer to avoid query to remove all versions because it will force Western developers to remove unknown browser (unknown for Western developers, but very popular in other countries).

So painful API is by design.

**Comment by emirotin** [comment] 2020-04-27 16:31
I understand this point but didn't you suggest I send a PR with it anyway?

I specifically am developing a site targeted at the very localized
auditory: Northern Europe. We truly don't have any UC, dolphin or QQ users
and don't want to spend resources on fixing bugs for these browsers. Asian
or African customers are not even legally allowed to use this site. The
tool can encourage users for some best practices but I think this one is a
bit controversial to stand in their way.

I can really live `with > 0` but if you think it's worth I'll try to add
support for `all` and `*` shortcuts.

**Comment by ai** [comment] 2020-04-27 17:26
> I specifically am developing a site targeted at the very localized auditory: Northern Europe.

I do not think that everyone should all browsers. My main idea is that you should think twice before removing the support of some browser.

If we will have simple and easy to use API, people will not think twice. They will remove the browser for a very small reason like “I never used it personally”.

You always have an option to remove the unnecessary browser. It will just use ugly syntax. So, on one hand, we have just syntax sugar for small amount of developers. But on the other, we have a lot of people in the world, who will not be able to visit global websites.

**Comment by emirotin** [comment] 2020-04-27 17:50
OK, I see your point and can relate.

I think the biggest concern left is that 'opera mini all' appears somewhere (other issues) and thus leaves the impression it's a valid syntax. And it's not logical it's only valid for a single browser (yeah I got it's because of the underlying caniuse but browserslist can have a special handling for it.

I'm fine to close this ticket but then what about your original comment to

> PR with adding all version to /index.js@master#L1067  and tests
?

**Comment by ai** [comment] 2020-04-27 19:55
> I think the biggest concern left is that 'opera mini all' appears somewhere (other issues) and thus leaves the impression it's a valid syntax. And it's not logical it's only valid for a single browser (yeah I got it's because of the underlying caniuse but browserslist can have special handling for it.

I totally agree. Unfortunately, this is Can I Use API which we can’t change :(

> I'm fine to close this ticket but then what about your original comment to

We do not need to close this issue. We still have an error of `not opera_mini all`. Browserslist returns `opera_mini all` and we should have an option to add `not` to any browsers returned from Browserslist.

Check the RegExp on the line at the link. You will find that it supports only `\d+` and `tp` versions, but not `all`.

**Comment by emirotin** [comment] 2020-04-27 20:41
> I totally agree. Unfortunately, this is Can I Use API which we can’t change :(

You can have extra parsing on top of that to normalize their API, no?

> Browserslist returns opera_mini all and we should have an option to add not to any browsers returned from Browserslist.

I think you've misunderstood, `not OperaMini all` works for me, the error I see is for Opera **Mobile** while Mini works just as I would expect

**Comment by ai** [comment] 2020-04-27 20:54
> You can have extra parsing on top of that to normalize their API, no?

I dream about it, but it is hard. All tools use Can I Use data.

> I think you've misunderstood, not OperaMini all works for me, the error I see is for Opera Mobile while Mini works just as I would expect

Got it. You need to use `not operamobile 46` or `not last 1 operamobile version`.

**Closed by ai** 2020-04-27 20:54 UTC

**Comment by emirotin** [comment] 2020-04-27 20:57
> You need to use not operamobile 46 or not last 1 operamobile version.

That I solved with `> 0` as mentioned in the original message as well.
