### ISSUE TITLE
Remove dependency range from `caniuse-lite`

### ISSUE THREAD

**Issue by Jameskmonger** [browserslist/browserslist#842] opened 2024-09-19 10:33 UTC
`caniuse-lite` and `caniuse-db` do not respect semantic versioning.

Recently, a breaking change was published under a patch update (`1.0.30001654` -> `1.0.30001655`)  (you can read more in these two issues: https://github.com/browserslist/caniuse-lite/issues/129, https://github.com/RJWadley/stylelint-no-unsupported-browser-features/issues/299)

It is therefore dangerous to accept a semantic version range in for `caniuse-lite`, `browserslist` has caused breaking changes to bleed into dependant projects due to this

**Comment by nhatlaso1** [comment] 2024-09-19 10:33
install this
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by Jameskmonger** [comment] 2024-09-19 10:34
> install this **dangerous link removed**
> 
> you may need to install the c compiler

Needless to say, do not click the link in the comment above

**Comment by ai** [comment] 2024-09-19 10:36
Locking to exact version will stop Autoprefixer/Babel to update prefixes/polyfills.

Queries like `>1%` will stop to work as expected because they will use year old data.

Manually checking every caniuse DB release and release a new Browserslist/Autoprefixer/Babel version which require a lot of my unpaid work, which is not fair.

Please, suggest the plan not a complaint since open source is a community.

**Comment by Jameskmonger** [comment] 2024-09-19 10:41
@ai This is fundamentally an issue with the release strategy of `caniuse`. Publishing data changes under patch versions is one thing, however they recently removed entire files which caused downstream breakages.

I have raised the issue here because I inherited the breakage through this project, and it's likely other users will arrive at your repo with the same issue, not because I expect you to do unpaid work to resolve this. As you say, open source is a community, so I came here to share the issue that I encountered.

**Comment by ai** [comment] 2024-09-19 10:48
I am going to close this issue, since I am already aware about it (it is not the first time when files was deleted or format was changed, BTW).

Raising the issue is not useful for the community. Maintainers need solutions, researches and help.

**Closed by ai** 2024-09-19 10:48 UTC

**Comment by Jameskmonger** [comment] 2024-09-19 10:50
Fair enough.

Users can pin their own versions e.g:

```
    "resolutions": {
        "caniuse-lite": "1.0.30001653"
    }
```

> Raising the issue is not useful for the community. Maintainers need solutions, researches and help.

Possibly someone else would have come along and shared some solution, research or help with the matter - you may want to add an issue template indicating that the author of an issue must be the one to also propose a solution, if that's your policy/expectation

**Comment by ai** [comment] 2024-09-19 10:55
> Users can pin their own versions

Yes, this is a solution.

But most of users use package manager lock file, so `caniuse-lite` anyway will update it only on explicit request (this is why I do not know whom need a pin).

> you may want to add an issue template indicating that the author of an issue must be the one to also propose a solution, if that's your policy/expectation

It highly depends. If it is an error inside my caniuse-lite or Browserslist, lack of solution is OK.

**Comment by CAM-Gerlach** [comment] 2024-09-21 22:36
> But most of users use package manager lock file, so caniuse-lite anyway will update it only on explicit request (this is why I do not know whom need a pin).

FYI, one example would be people and project using it through other tooling, e.g. as part of a number of [pre-commit](https://pre-commit.com) hooks, as the standard way to configure other tools that have behavior that varies by browser and version, or that check compatibility with a specific browser/version range. Across the [Spyder](https://github.com/spyder-ide) open source organization, we use it for instance with the `stylelint-no-unsupported-browser-features` hook on a number of our repos, where this problem cropped up for us.

It wasn't that difficult to manually pin it to the latest working version until the issue is fixed, but as maintainers ourselves doing so across many hooks and many projects that use them consumes a substantial amount of time.

> Manually checking every caniuse DB release and release a new Browserslist/Autoprefixer/Babel version which require a lot of my unpaid work, which is not fair.

Certainly agreed that's not a sustainable use of maintainer time. At least in theory, you could potentially use a GitHub Action, set to run every e.g. week, month, etc., that would run this package's tests against the latest caniuse and if it succeeds, bump the version (via. e.g. a regex), or if it fails, let you know there's a problem (I've done something similar in a few different workflows in the past). However, besides the non-trivial amount of setup, if the error isn't caught by this package's tests but rather with its consumers, then it wouldn't be caught here (which suggests its indeed something that doesn't make sense to fix here).

> Raising the issue is not useful for the community. Maintainers need solutions, researches and help.

If this is your choice for your project (as is your right), it might be worth making that clear in the issue template, given the overwhelming majority of GitHub FOSS projects I've been part of or contributed to do not reject issues and chastise the author for submitting an issue if it doesn't already have a detailed solution that the maintainer likes. And for what its worth, as a long-time FOSS maintainer myself [^1], my own perspective on what issues and that of the many projects I'm a part of aligns closely with that of @Jameskmonger .

[^1]: Core developer of the Python programming language and the Spyder IDE/scientific environment, among other projects, with a main focus these days on the administrative, mentorship, outreach/community management and sustainability aspects beyond just the code

FYI, quick sidenote—seemed this was accidently closed with the "as completed" status rather than the correct "invalid" one; you can reclose want to fix that.
